; Always the first three methods
IUnknown_QueryInterface	textequ <qword ptr [rbx + 000h]>
IUnknown_AddRef			textequ <qword ptr [rbx + 008h]>
IUnknown_Release		textequ <qword ptr [rbx + 010h]>

;ID2D1Factory
ID2D1Factory_ReloadSystemMetrics				textequ <qword ptr [rbx + 018h]>
ID2D1Factory_GetDesktopDpi						textequ <qword ptr [rbx + 020h]>
ID2D1Factory_CreateRectangleGeometry			textequ <qword ptr [rbx + 028h]>
ID2D1Factory_CreateRoundedRectangleGeometry		textequ <qword ptr [rbx + 030h]>
ID2D1Factory_CreateEllipseGeometry				textequ <qword ptr [rbx + 038h]>
ID2D1Factory_CreateGeometryGroup				textequ <qword ptr [rbx + 040h]>
ID2D1Factory_CreateTransformedGeometry			textequ <qword ptr [rbx + 048h]>
ID2D1Factory_CreatePathGeometry					textequ <qword ptr [rbx + 050h]>
ID2D1Factory_CreateStrokeStyle					textequ <qword ptr [rbx + 058h]>
ID2D1Factory_CreateDrawingStateBlock			textequ <qword ptr [rbx + 060h]>
ID2D1Factory_CreateWicBitmapRenderTarget		textequ <qword ptr [rbx + 068h]>
ID2D1Factory_CreateHwndRenderTarget				textequ <qword ptr [rbx + 070h]>
ID2D1Factory_CreateDxgiSurfaceRenderTarget		textequ <qword ptr [rbx + 078h]>
ID2D1Factory_CreateDCRenderTarget				textequ <qword ptr [rbx + 080h]>
ID2D1Factory_CreateRectangleGeometry2			textequ <qword ptr [rbx + 088h]>
ID2D1Factory_CreateRoundedRectangleGeometry2	textequ <qword ptr [rbx + 090h]>
ID2D1Factory_CreateEllipseGeometry2				textequ <qword ptr [rbx + 098h]>
ID2D1Factory_CreateTransformedGeometry2			textequ <qword ptr [rbx + 0a0h]>
ID2D1Factory_CreateStrokeStyle2					textequ <qword ptr [rbx + 0a8h]>
ID2D1Factory_CreateDrawingStateBlock2			textequ <qword ptr [rbx + 0b0h]>
ID2D1Factory_CreateDrawingStateBlock3			textequ <qword ptr [rbx + 0b8h]>
ID2D1Factory_CreateWicBitmapRenderTarget2		textequ <qword ptr [rbx + 0c0h]>
ID2D1Factory_CreateHwndRenderTarget2			textequ <qword ptr [rbx + 0c8h]>
ID2D1Factory_CreateDxgiSurfaceRenderTarget2		textequ <qword ptr [rbx + 0d0h]>

;ID2D1Resource
ID2D1Resource_GetFactory						textequ <qword ptr [rbx + 018h]>
;ID2D1RenderTarget virtual method table
ID2D1RenderTarget_CreateBitmap					textequ <qword ptr [rbx + 020h]>
ID2D1RenderTarget_CreateBitmapFromWicBitmap		textequ <qword ptr [rbx + 028h]>
ID2D1RenderTarget_CreateSharedBitmap			textequ <qword ptr [rbx + 030h]>
ID2D1RenderTarget_CreateBitmapBrush				textequ <qword ptr [rbx + 038h]>
ID2D1RenderTarget_CreateSolidColorBrush			textequ <qword ptr [rbx + 040h]>
ID2D1RenderTarget_CreateGradientStopCollection	textequ <qword ptr [rbx + 048h]>
ID2D1RenderTarget_CreateLinearGradientBrush		textequ <qword ptr [rbx + 050h]>
ID2D1RenderTarget_CreateRadialGradientBrush		textequ <qword ptr [rbx + 058h]>
ID2D1RenderTarget_CreateCompatibleRenderTarget	textequ <qword ptr [rbx + 060h]>
ID2D1RenderTarget_CreateLayer					textequ <qword ptr [rbx + 068h]>
ID2D1RenderTarget_CreateMesh					textequ <qword ptr [rbx + 070h]>
ID2D1RenderTarget_DrawLine						textequ <qword ptr [rbx + 078h]>
ID2D1RenderTarget_DrawRectangle					textequ <qword ptr [rbx + 080h]>
ID2D1RenderTarget_FillRectangle					textequ <qword ptr [rbx + 088h]>
ID2D1RenderTarget_DrawRoundedRectangle			textequ <qword ptr [rbx + 090h]>
ID2D1RenderTarget_FillRoundedRectangle			textequ <qword ptr [rbx + 098h]>
ID2D1RenderTarget_DrawEllipse					textequ <qword ptr [rbx + 0a0h]>
ID2D1RenderTarget_FillEllipse					textequ <qword ptr [rbx + 0a8h]>
ID2D1RenderTarget_DrawGeometry					textequ <qword ptr [rbx + 0b0h]>
ID2D1RenderTarget_FillGeometry					textequ <qword ptr [rbx + 0b8h]>
ID2D1RenderTarget_FillMesh						textequ <qword ptr [rbx + 0c0h]>
ID2D1RenderTarget_FillOpacityMask				textequ <qword ptr [rbx + 0c8h]>
ID2D1RenderTarget_DrawBitmap					textequ <qword ptr [rbx + 0d0h]>
ID2D1RenderTarget_DrawText						textequ <qword ptr [rbx + 0d8h]>
ID2D1RenderTarget_DrawTextLayout				textequ <qword ptr [rbx + 0e0h]>
ID2D1RenderTarget_DrawGlyphRun					textequ <qword ptr [rbx + 0e8h]>
ID2D1RenderTarget_SetTransform					textequ <qword ptr [rbx + 0f0h]>
ID2D1RenderTarget_GetTransform					textequ <qword ptr [rbx + 0f8h]>
ID2D1RenderTarget_SetAntialiasMode				textequ <qword ptr [rbx + 100h]>
ID2D1RenderTarget_GetAntialiasMode				textequ <qword ptr [rbx + 108h]>
ID2D1RenderTarget_SetTextAntialiasMode			textequ <qword ptr [rbx + 110h]>
ID2D1RenderTarget_GetTextAntialiasMode			textequ <qword ptr [rbx + 118h]>
ID2D1RenderTarget_SetTextRenderingParams		textequ <qword ptr [rbx + 120h]>
ID2D1RenderTarget_GetTextRenderingParams		textequ <qword ptr [rbx + 128h]>
ID2D1RenderTarget_SetTags						textequ <qword ptr [rbx + 130h]>
ID2D1RenderTarget_GetTags						textequ <qword ptr [rbx + 138h]>
ID2D1RenderTarget_PushLayer						textequ <qword ptr [rbx + 140h]>
ID2D1RenderTarget_PopLayer						textequ <qword ptr [rbx + 148h]>
ID2D1RenderTarget_Flush							textequ <qword ptr [rbx + 150h]>
ID2D1RenderTarget_SaveDrawingState				textequ <qword ptr [rbx + 158h]>
ID2D1RenderTarget_RestoreDrawingState			textequ <qword ptr [rbx + 160h]>
ID2D1RenderTarget_PushAxisAlignedClip			textequ <qword ptr [rbx + 168h]>
ID2D1RenderTarget_PopAxisAlignedClip			textequ <qword ptr [rbx + 170h]>
ID2D1RenderTarget_Clear							textequ <qword ptr [rbx + 178h]>
ID2D1RenderTarget_BeginDraw						textequ <qword ptr [rbx + 180h]>
ID2D1RenderTarget_EndDraw						textequ <qword ptr [rbx + 188h]>
ID2D1RenderTarget_GetPixelFormat				textequ <qword ptr [rbx + 190h]>
ID2D1RenderTarget_SetDpi						textequ <qword ptr [rbx + 198h]>
ID2D1RenderTarget_GetDpi						textequ <qword ptr [rbx + 1a0h]>
ID2D1RenderTarget_GetSize						textequ <qword ptr [rbx + 1a8h]>
ID2D1RenderTarget_GetPixelSize					textequ <qword ptr [rbx + 1b0h]>
ID2D1RenderTarget_GetMaximumBitmapSize			textequ <qword ptr [rbx + 1b8h]>
ID2D1RenderTarget_IsSupported					textequ <qword ptr [rbx + 1c0h]>
ID2D1RenderTarget_CreateBitmap2                 textequ <qword ptr [rbx + 1c8h]>
ID2D1RenderTarget_CreateBitmap3                 textequ <qword ptr [rbx + 1d0h]>
ID2D1RenderTarget_CreateBitmapFromWicBitmap2    textequ <qword ptr [rbx + 1d8h]>
ID2D1RenderTarget_CreateBitmapFromWicBitmap3    textequ <qword ptr [rbx + 1e0h]>
ID2D1RenderTarget_CreateBitmapBrush2            textequ <qword ptr [rbx + 1e8h]>
ID2D1RenderTarget_CreateBitmapBrush3            textequ <qword ptr [rbx + 1f0h]>
ID2D1RenderTarget_CreateBitmapBrush4            textequ <qword ptr [rbx + 1f8h]>
ID2D1RenderTarget_CreateSolidColorBrush2        textequ <qword ptr [rbx + 200h]>
ID2D1RenderTarget_CreateSolidColorBrush3        textequ <qword ptr [rbx + 208h]>
ID2D1RenderTarget_CreateGradientStopCollection2 textequ <qword ptr [rbx + 210h]>
ID2D1RenderTarget_CreateLinearGradientBrush2    textequ <qword ptr [rbx + 218h]>
ID2D1RenderTarget_CreateLinearGradientBrush3    textequ <qword ptr [rbx + 220h]>
ID2D1RenderTarget_CreateRadialGradientBrush2    textequ <qword ptr [rbx + 228h]>
ID2D1RenderTarget_CreateRadialGradientBrush3    textequ <qword ptr [rbx + 230h]>
ID2D1RenderTarget_CreateCompatibleRenderTarget2 textequ <qword ptr [rbx + 238h]>
ID2D1RenderTarget_CreateCompatibleRenderTarget3 textequ <qword ptr [rbx + 240h]>
ID2D1RenderTarget_CreateCompatibleRenderTarget4 textequ <qword ptr [rbx + 248h]>
ID2D1RenderTarget_CreateCompatibleRenderTarget5 textequ <qword ptr [rbx + 250h]>
ID2D1RenderTarget_CreateCompatibleRenderTarget6	textequ <qword ptr [rbx + 258h]>
ID2D1RenderTarget_CreateLayer2                  textequ <qword ptr [rbx + 260h]>
ID2D1RenderTarget_CreateLayer3                  textequ <qword ptr [rbx + 268h]>
ID2D1RenderTarget_DrawRectangle2                textequ <qword ptr [rbx + 270h]>
ID2D1RenderTarget_FillRectangle2                textequ <qword ptr [rbx + 278h]>
ID2D1RenderTarget_DrawRoundedRectangle2         textequ <qword ptr [rbx + 280h]>
ID2D1RenderTarget_FillRoundedRectangle2         textequ <qword ptr [rbx + 288h]>
ID2D1RenderTarget_DrawEllipse2                  textequ <qword ptr [rbx + 290h]>
ID2D1RenderTarget_FillEllipse2                  textequ <qword ptr [rbx + 298h]>
ID2D1RenderTarget_FillOpacityMask2              textequ <qword ptr [rbx + 2a0h]>
ID2D1RenderTarget_DrawBitmap2                   textequ <qword ptr [rbx + 2a8h]>
ID2D1RenderTarget_DrawBitmap3                   textequ <qword ptr [rbx + 2b0h]>
ID2D1RenderTarget_SetTransform2                 textequ <qword ptr [rbx + 2b8h]>
ID2D1RenderTarget_PushLayer2                    textequ <qword ptr [rbx + 2c0h]>
ID2D1RenderTarget_PushAxisAlignedClip2          textequ <qword ptr [rbx + 2c8h]>
ID2D1RenderTarget_Clear2                        textequ <qword ptr [rbx + 2d0h]>
ID2D1RenderTarget_DrawText2                     textequ <qword ptr [rbx + 2d8h]>
ID2D1RenderTarget_IsSupported2                  textequ <qword ptr [rbx + 2e0h]>
;ID2D1HwndRenderTarget
ID2D1HwndRenderTarget_CheckWindowState			textequ <qword ptr [rbx + 2e8h]>
ID2D1HwndRenderTarget_Resize					textequ <qword ptr [rbx + 2f0h]>
ID2D1HwndRenderTarget_GetHwnd					textequ <qword ptr [rbx + 2f8h]>
ID2D1HwndRenderTarget_Resize2					textequ <qword ptr [rbx + 300h]>